#include "../../Cmd.h"

const wxSize Cmd::VERTICAL_SLIDER_DRAW_GET_MAIN_SIZE() {
	const wxSize VERTICAL_SLIDER_BACKGROUND_SIZE = this->VERTICAL_SLIDER_DRAW_GET_BACKGROUND_SIZE(); 

	return wxSize(
		VERTICAL_SLIDER_BACKGROUND_SIZE.x - this->VERTICAL_SLIDER_MAIN_DIFFERENCE_FROM_BACKGROUND_X, (VERTICAL_SLIDER_BACKGROUND_SIZE.y - this->VERTICAL_SLIDER_MAIN_DIFFERENCE_FROM_BACKGROUND_Y) / 5
	);
}

const wxPoint Cmd::VERTICAL_SLIDER_DRAW_GET_MAIN_POSITION() {
	const wxSize VERTICAL_SLIDER_MAIN_SIZE = this->VERTICAL_SLIDER_DRAW_GET_MAIN_SIZE(); 
	const wxSize VERTICAL_SLIDER_BACKGROUND_SIZE = this->VERTICAL_SLIDER_DRAW_GET_BACKGROUND_SIZE();
	const wxPoint VERTICAL_SLIDER_BACKGROUND_POSITION = this->VERTICAL_SLIDER_DRAW_GET_BACKGROUND_POSITION();

	const int VERTICAL_SLIDER_MAIN_LENGHT_DIFFERENCE = VERTICAL_SLIDER_BACKGROUND_SIZE.x - VERTICAL_SLIDER_MAIN_SIZE.x;
	const int VERTICAL_SLIDER_MAIN_HEIGHT_DIFFERENCE = this->VERTICAL_SLIDER_MAIN_DIFFERENCE_FROM_BACKGROUND_Y / 2;

	const int VERTICAL_SLIDER_MAIN_POSITION_X = VERTICAL_SLIDER_BACKGROUND_POSITION.x + VERTICAL_SLIDER_MAIN_LENGHT_DIFFERENCE / 2;
	const int VERTICAL_SLIDER_MAIN_POSITION_Y = VERTICAL_SLIDER_BACKGROUND_POSITION.y + this->VERTICAL_SLIDER_SCROLL + VERTICAL_SLIDER_MAIN_HEIGHT_DIFFERENCE; 

	return wxPoint(
		VERTICAL_SLIDER_MAIN_POSITION_X, VERTICAL_SLIDER_MAIN_POSITION_Y
	);
}

const void Cmd::VERTICAL_SLIDER_DRAW_MAIN(
	wxPaintDC* dc 
) {
	dc->SetBrush(this->VERTICAL_SLIDER_COLOR_MAIN);
	dc->SetPen(this->VERTICAL_SLIDER_COLOR_MAIN);

	dc->DrawRoundedRectangle(wxRect(
		this->VERTICAL_SLIDER_DRAW_GET_MAIN_POSITION(), this->VERTICAL_SLIDER_DRAW_GET_MAIN_SIZE()
	), 1.5);
}