#include "../Cmd.h"

const void Cmd::SETUP_MOUSE_INTERFACE_FONT(
	const std::string& _FACENAME, const int& _SIZE
) {
	this->MOUSE_INTERFACE_FONT_FACENAME = _FACENAME;
	this->MOUSE_INTERFACE_FONT_SIZE = _SIZE; 
}

const void Cmd::SETUP_MOUSE_INTERFACE_ADDITIONAL_RESERVED_SPACE(
	const int& SPACE
) {
	this->MOUSE_INTERFACE_ADDITIONAL_RESERVED_SPACE = SPACE; 
}

const void Cmd::SETUP_MOUSE_INTERFACE_RESERVED_SPACE(
	const int& FONT_SIZE
) {
	this->MOUSE_INTERFACE_RESERVED_SPACE = this->MOUSE_INTERFACE_ADDITIONAL_RESERVED_SPACE + FONT_SIZE;
}

const void Cmd::SETUP_MOUSE_INTERFACE_COLORS(
	const int& TEXT_R, const int& TEXT_G, const int& TEXT_B, const int& BACKGROUND_R, const int& BACKGROUND_B, const int& BACKGROUND_G
) {
	this->MOUSE_INTERFACE_COLOR_BACKGROUND = wxColor(BACKGROUND_R, BACKGROUND_G, BACKGROUND_B);
	this->MOUSE_INTERFACE_COLOR_TEXT = wxColor(TEXT_R, TEXT_G, TEXT_B);
}